version: '3.8'

services:
  simulator:
    build:
      context: .
      dockerfile: simulator/Dockerfile
    container_name: simulator
    privileged: true
    ports:
      - "8000:8000"
    networks:
      - simulator
    volumes:
      - shared-builds:/opt/shared-builds

  flight-controller:
    build:
      context: .
      dockerfile: flight-controller/Dockerfile
    container_name: flight-controller
    privileged: true
    networks:
      - simulator
    volumes:
      - shared-builds:/opt/shared-builds

  companion-computer:
    build:
      context: .
      dockerfile: companion-computer/Dockerfile
    container_name: companion-computer
    privileged: true
    ports:
      - "3000:3000"
    networks:
      - simulator
    volumes:
      - shared-builds:/opt/shared-builds

  ground-control-station:
    build:
      context: .
      dockerfile: ground-control-station/Dockerfile
    container_name: ground-control-station
    privileged: true
    ports:
      - "8080:8080"
    networks:
      - simulator
    volumes:
      - shared-builds:/opt/shared-builds

  qgc:
    image: kestr3l/qgc-app:nobg-4.0.0
    build:
      context: .
      dockerfile: qgc/Dockerfile
    container_name: qgc-container
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - shared-builds:/opt/shared-builds
    networks:
      - simulator

networks:
  simulator:
    driver: bridge

volumes:
  shared-builds: